#!/usr/bin/env python3
"""Read-only inventory checks for an explicitly generated opening source tree.

This is not a composer, installer, compiled-bank validator or runtime test.
It deliberately does not weaken the default native script SHA inventory.
"""

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import stat
import subprocess


def safe_relative(name):
    path = PurePosixPath(name)
    if (not name or "\\" in name or path.is_absolute()
            or any(part in ("", ".", "..") for part in name.split("/"))
            or str(path) != name):
        raise ValueError(f"Unsafe inventory path: {name!r}")
    return path


def regular_bytes(root, name):
    relative = safe_relative(name)
    current = Path(root)
    if current.is_symlink() or not current.is_dir():
        raise ValueError("Root must be a real directory")
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"Symlink forbidden in audited source path: {name}")
    if not stat.S_ISREG(current.stat().st_mode):
        raise ValueError(f"Not a regular source file: {name}")
    return current.read_bytes()


def digest(data):
    return hashlib.sha256(data).hexdigest()


# Only these appended native sources belong to the episode. Build-preparation
# extras are NOT discovered with a permissive recursive glob.
EPISODE_ADDITIONS = (
    "files/data/mmodel/mmodel/mmodel_00000863.NSBTX",
    "files/data/mmodel/mmodel/mmodel_00000864.NSBTX",
    "files/data/mmodel/mmodel/mmodel_00000865.NSBTX",
    "files/fielddata/eventdata/zone_event/491_HOENN_LAB_DEBUG.json",
    "files/fielddata/eventdata/zone_event/492_LITTLEROOT_TOWN_TRAVEL.json",
    "files/fielddata/eventdata/zone_event/493_ROUTE_101_TRAVEL.json",
    "files/fielddata/mapmatrix/map_matrix/map_matrix_0288_HOENN_LAB.bin",
    "files/fielddata/mapmatrix/map_matrix/map_matrix_0289_LITTLEROOT_TOWN.bin",
    "files/fielddata/mapmatrix/map_matrix/map_matrix_0290_ROUTE_101.bin",
    "files/fielddata/script/scr_seq/scr_seq_0966_route101_opening_hdr.s",
)

# Evidence for excluded untracked native outputs. Compiler executables/SDKs,
# object/dependency files and private reports/backups are never source inputs.
DERIVED_RULES = {
    "files/application/zukanlist/zkn_data/zukan_hw_data/zukan_hw_data_1.bin":
        "files/application/zukanlist/zkn_data/zukan_hw_data.mk: edition ln -sf recipe",
    "files/application/zukanlist/zkn_data/zukan_hw_data_gold.narc":
        "files/application/zukanlist/zkn_data/zukan_hw_data.mk: NARC recipe",
    "files/application/zukanlist/zkn_data/zukan_hw_data_gold.naix":
        "files/application/zukanlist/zkn_data/zukan_hw_data.mk: NARC --index-namespace",
    "files/application/zukanlist/zkn_data/zukan_enc_gold.s":
        "files/application/zukanlist/zkn_data/zukan_enc.mk: JSONPROC intermediate",
    "lib/include/nitro/fx/fx_const.h": "Makefile: FX_CONST_H generated by MKFXCONST",
    "files/a/0/7/5": "filesystem.mk: arc_strip_name zukan_hw_data edition archive",
}


def native_names(root):
    tracked = subprocess.check_output(
        ["git", "-C", str(root), "ls-tree", "-rz", "--name-only", "HEAD"]
    ).decode().rstrip("\0").split("\0")
    return sorted(set(EPISODE_ADDITIONS).union(
        name for name in tracked
        if name.startswith(("asm/", "src/", "include/", "lib/", "files/", "sub/",
                            "heartgold.us/", "soulsilver.us/", "tools/"))
        or name in {
            "Makefile", "CMakeLists.txt", "binutils.mk", "common.mk", "config.mk",
            "filesystem.mk", "graphics_files_rules.mk", "platform.mk",
            "charmap.txt", "global.inc", "main.lsf", "rom.rsf", "scr_seq.sha1",
            "expansion/baseline.json",
        }))


def native_inputs(root, tree):
    """Complete native input inventory; NOT a compiled-bank acceptance policy."""
    return {name: digest(regular_bytes(tree, name)) for name in native_names(root)}


EPISODE_SCRIPT_BANKS = frozenset({
    "scr_seq_0843_T20R0101.bin",
    "scr_seq_0965_hoenn_reward.bin",
    "scr_seq_0966_route101_opening_hdr.bin",
})


def verify_compiled_inventory(directory, baseline_manifest, episode_sha1):
    """Opt-in bank audit; caller supplies independently approved episode hashes.

    No compilation is performed. The default build_native_field_scripts policy
    and scr_seq.sha1 are untouched. Every non-episode bank retains its original
    SHA1 requirement; all three changed/appended banks require explicit pins.
    """
    if set(episode_sha1) != EPISODE_SCRIPT_BANKS:
        raise ValueError("Exactly the three episode bank pins are required")
    if any(len(value) != 40 or any(c not in "0123456789abcdef" for c in value)
           for value in episode_sha1.values()):
        raise ValueError("Invalid episode SHA1")
    baseline = Path(baseline_manifest).read_bytes()
    if digest(baseline) != "1d71988ee54402fcf52adcb822f01ce6c3cc75f88b3e478150664f0d96ee52be":
        raise ValueError("Default compiled-bank manifest differs from pinned baseline")
    expected = {}
    for line in baseline.decode().splitlines():
        expected_hash, name = line.split()
        name = Path(name.lstrip("*")).name
        if name in expected:
            raise ValueError("Duplicate baseline script bank")
        expected[name] = expected_hash
    if len(expected) != 966 or "scr_seq_0966_route101_opening_hdr.bin" in expected:
        raise ValueError("Expected unchanged default 966-bank inventory")
    expected.update(episode_sha1)
    directory = Path(directory)
    if {p.name for p in directory.glob("*.bin")} != set(expected):
        raise ValueError("Compiled episode bank inventory differs")
    for name, expected_hash in expected.items():
        if hashlib.sha1(regular_bytes(directory, name)).hexdigest() != expected_hash:
            raise ValueError(f"Compiled script mismatch: {name}")
    return {"banks": len(expected), "unchanged_default_banks": 964,
            "explicit_episode_banks": sorted(episode_sha1)}


def compare(root, generated):
    """Compare every committed regular source file, not an incremental subset.

    Generated extras are inventoried separately. A symlink is recorded as such,
    never followed; deleted tracked files and changed symlinks remain explicit.
    Git metadata and Python caches are not native inputs.
    """
    root, generated = Path(root), Path(generated)
    if root.resolve() == generated.resolve():
        raise ValueError("Generated tree must be distinct from the checkout")
    revision = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()
    records = subprocess.check_output(
        ["git", "-C", str(root), "ls-tree", "-rz", "--full-tree", "HEAD"])
    tracked, changes = set(), {}
    for record in records.split(b"\0"):
        if not record:
            continue
        metadata, encoded_name = record.split(b"\t", 1)
        mode, kind, oid = metadata.split()
        name = encoded_name.decode("utf-8")
        safe_relative(name)
        tracked.add(name)
        target = generated / name
        before = subprocess.check_output(
            ["git", "-C", str(root), "cat-file", "blob", oid.decode()])
        if mode == b"120000":
            after = target.readlink().as_posix().encode() if target.is_symlink() else None
        elif kind == b"blob":
            after = regular_bytes(generated, name) if target.exists() or target.is_symlink() else None
        else:
            raise ValueError(f"Unsupported tracked entry: {name}")
        if before != after:
            changes[name] = {
                "before": digest(before),
                "after": None if after is None else digest(after),
                "kind": "symlink" if mode == b"120000" else "regular",
            }
    extras = {}
    for path in sorted(generated.rglob("*")):
        name = path.relative_to(generated).as_posix()
        if any(part in (".git", "__pycache__") for part in path.relative_to(generated).parts):
            continue
        if name in tracked:
            continue
        if name.startswith("tools/mwccarm/"):
            # These owner-local compiler/SDK/license files are not source
            # provenance and must never be read into a distributable inventory.
            extras[name] = {"kind": "excluded-user-local-proprietary-toolchain"}
            continue
        if path.is_symlink():
            # Inventory is not installation approval: record, never follow.
            extras[name] = {"kind": "derived-symlink" if name in DERIVED_RULES
                            else "unclassified-symlink",
                            "target": path.readlink().as_posix()}
            if name in DERIVED_RULES:
                extras[name]["rule"] = DERIVED_RULES[name]
            continue
        if path.is_dir():
            continue
        extras[name] = ({"kind": "derived", "rule": DERIVED_RULES[name]}
                        if name in DERIVED_RULES else digest(regular_bytes(generated, name)))
    return {
        "status": "read-only-generated-source-inventory-not-runtime-proof",
        "base_commit": revision,
        "tracked_entries": len(tracked),
        "changed_tracked": changes,
        "generated_extras": extras,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--generated", required=True, type=Path)
    args = parser.parse_args()
    print(json.dumps(compare(args.root, args.generated), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()