/* Generated by import_fakemon_text.py. Indexed species - SPECIES_VOLTUFF. */
#ifndef POKEHEARTGOLD_FAKEMON_DEX_PAGES_H
#define POKEHEARTGOLD_FAKEMON_DEX_PAGES_H
static const u8 sFakemonDexPageCounts[11] = { 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2 };
#endif
