#!/usr/bin/env python3
"""Install approved names, page-sized Dex prose and dimensions; keep stock rows verbatim."""
import copy,json,re,textwrap
from pathlib import Path
from xml.sax.saxutils import escape
ROOT=Path(__file__).resolve().parents[2]
meta=json.loads((ROOT/'files/fakemon/species.json').read_text())
mons=sorted((m for line in meta['lines'] for m in line['designs']),key=lambda m:m['engine_species_id'])
# HGSS uses uppercase species names both in name banks and in running text.
# Keep the design metadata's readable spelling; transform only game strings.
def game_species_names(text):
    for mon in mons:
        text=re.sub(r'\b'+re.escape(mon['name'])+r'\b',mon['name'].upper(),text)
    return text
pages={m['engine_species_id']:['\\n'.join(lines[i:i+3]) for i in range(0,len(lines),3)] for m in mons for lines in [textwrap.wrap(game_species_names(m['pokedex_details']['entry_text']),width=32)]}
def extend(bank,values):
    path=ROOT/f'files/msgdata/msg/msg_{bank:04}.gmm'
    source=path.read_text()
    # Idempotent: only remove our own prior generated rows.
    source=re.sub(r'\n\t<!-- BEGIN FAKEMON -->.*?\t<!-- END FAKEMON -->\n','',source,flags=re.S)
    indexes=[int(x) for x in re.findall(r'<row[^>]+index="(\d+)"',source)]
    last=max(indexes)
    assert last<1076
    body='\n\t<!-- BEGIN FAKEMON -->\n'
    for i in range(last+1,max(values)+1):
        text=escape(values.get(i,''))
        body+=f'\t<row id="msg_{bank:04}_fakemon_{i:05}" index="{i}">\n\t\t<attribute name="window_context_name">used</attribute>\n\t\t<language name="English">{text}</language>\n\t</row>\n'
    body+='\t<!-- END FAKEMON -->\n'
    path.write_text(source.replace('</body>',body+'</body>'))
for bank in [237,817,818,819,820,821,822]: extend(bank,{m['engine_species_id']:m['name'].upper() for m in mons})
extend(238,{m['engine_species_id']:('an' if m['name'][0] in 'AEIOU' else 'a')+' {COLOR 255}'+m['name'].upper()+'{COLOR 0}' for m in mons})
for bank in range(803,812):
    values={m['engine_species_id']+11*page:text for m in mons for page,text in enumerate(pages[m['engine_species_id']])}
    extend(bank,values)
for bank in [812,813]:extend(bank,{m['engine_species_id']:f"{m['pokedex_details']['weight_hectograms']/10*2.2046226218:.1f} lbs." for m in mons})
for bank in [814,815]:
    values={}
    for m in mons:
        inches=round(m['pokedex_details']['height_decimetres']/10/0.0254)
        values[m['engine_species_id']]=f'{inches//12}’{inches%12:02d}”'
    extend(bank,values)
for bank in [816,823,824,825,826,827,828]:extend(bank,{m['engine_species_id']:m['pokedex_details']['classification'] for m in mons})
header='/* Generated by import_fakemon_text.py. Indexed species - SPECIES_VOLTUFF. */\n#ifndef POKEHEARTGOLD_FAKEMON_DEX_PAGES_H\n#define POKEHEARTGOLD_FAKEMON_DEX_PAGES_H\nstatic const u8 sFakemonDexPageCounts[11] = { '+', '.join(str(len(pages[m['engine_species_id']])) for m in mons)+' };\n#endif\n'
(ROOT/'include/fakemon_dex_pages.h').write_text(header)
# The native dimensions API indexes tables by species, so preserve all existing
# records and add safe zero-sized records for the reserved ID gap.
path=ROOT/'files/application/zukanlist/zkn_data/zukan_data.json'
data=json.loads(path.read_text()); rows=data['mon_stats'][:494]
blank=copy.deepcopy(rows[0]);blank.update(species='SPECIES_NONE',height=0,weight=0)
while len(rows)<1087:rows.append(copy.deepcopy(blank))
for m in mons:
    row=copy.deepcopy(blank);sid=m['engine_species_id'];details=m['pokedex_details']
    row.update(species='SPECIES_'+m['key'].upper(),height=details['height_decimetres'],weight=details['weight_hectograms'],body_style=4 if m['key']=='ragnaroc' else 5 if m['breeding']['hatch_species']=='sedgling' else 2 if m['breeding']['hatch_species']=='voltuff' else 0,scale_f=256,scale_m=256,mon_scale_f=256,mon_scale_m=256,ypos_f=8,ypos_m=8,mon_ypos_f=8,mon_ypos_m=8)
    rows[sid]=row
data["mon_stats"]=rows
path.write_text(json.dumps(data,indent=4)+"\n")
print("Installed names, full approved paged entries and dimensions for eleven species.")
